# Generated by Django 4.1.5 on 2023-03-03 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DH11_SENSOR",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("c_temp", models.FloatField(default=0)),
                ("f_temp", models.FloatField(default=0)),
                ("hum", models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="RESET_BUTTON",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("clicks_in_time", models.IntegerField(default=0)),
                ("time_clicked", models.DateTimeField(verbose_name="date pushed")),
            ],
        ),
    ]
