# Generated by Django 4.1.5 on 2023-03-03 16:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("esp32_dropplet", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="dh11_sensor",
            name="reg_check",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
