# Generated by Django 4.1.5 on 2023-03-27 02:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("esp32_dropplet", "0003_rename_reg_check_dh11_sensor_check_time"),
    ]

    operations = [
        migrations.RemoveField(model_name="reset_button", name="clicks_in_time",),
        migrations.AddField(
            model_name="reset_button",
            name="reason_clicked",
            field=models.TextField(default="System freeze"),
        ),
        migrations.AlterField(
            model_name="reset_button",
            name="time_clicked",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
